CREATE TABLE "encrypted_text" (
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1),
    "WORKFLOW_ID" INT NOT NULL REFERENCES app."workflow"(ID),
    "ENCRYPTED_TEXT" VARCHAR(250) NOT NULL,
    "STATUS" BOOLEAN DEFAULT FALSE NOT NULL,
    "DATE_ENTERED" VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);