CREATE TABLE "logs" (
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1),
    "USERID" INT NOT NULL REFERENCES app."users"(ID),
    "WORKFLOW_ID" INT NOT NULL REFERENCES app."workflow"(ID),
    "ENCRYPTED_TEXT" VARCHAR(256) NOT NULL,
    "DECRYPTED_TEXT" VARCHAR(256),
    PRIMARY KEY (ID)
);