CREATE TABLE "users" (
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1),
    "USERNAME" VARCHAR(30) NOT NULL,
    "PASSWORD" VARCHAR(50) NOT NULL,
    "LAST_LOGIN" VARCHAR(10),
    "IS_ACTIVE" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID),
    UNIQUE(username)
);