CREATE TABLE "workflow" (
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1),
    "USERID" INT NOT NULL REFERENCES app."users"(ID),
    "STATUS" BOOLEAN DEFAULT FALSE NOT NULL,
    "DATE_ENTERED" VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);